### ISSUE TITLE
ObjectLoader should be replaced with GLTFLoader

### ISSUE THREAD

**Issue by rtpHarry** [paulmg/ThreeJS-Webpack-ES6-Boilerplate#12]
ObjectLoader is supported and is going to be supported for a long time, but there has been a significant shift in the loaders over the last few releases:

- https://threejs.org/docs/#manual/introduction/Loading-3D-models

The packaged export tools have been removed from Three.js and replaced with recommendations to standardise on gltf format.

This caught me out for a while as I am out of my depth with Three and ES6 still at the moment. I ended up realising that I needed to add an extra npm package, `"three-gltf-loader": "^1.93.0",` so that I could then `import GLTFLoader from 'three-gltf-loader';` from within `Model.js` and use it. 

I'm not sure if this was the best way to do it and I have certainly misunderstood something because at the moment I am staring at the code trying to figure out why, even after the LoadingManager has given the all-clear, that somehow my models are not quite ready to be accessed. I think somewhere I am not correctly waiting for a Promise to complete so this sample would really help me.

**Comment by paulmg** [comment]
Yeah good point, I think someone else had an issue with the loader and blender export. I'll take a look at updating the loader when I get a chance. Feel free to create a PR with your changes if you'd like. Thanks.
