### ISSUE TITLE
retina issue on iMac 5k

### ISSUE THREAD

**Issue by lucaskuzma** [paulmg/ThreeJS-Webpack-ES6-Boilerplate#13]
https://github.com/paulmg/ThreeJS-Webpack-ES6-Boilerplate/blob/337e21226b15906f3c122e45a12dd634181d17e7/src/js/app/components/camera.js#L24

I haven't tested elsewhere, but this math looks a little odd. It multiplies the ratio of w/h by dpr twice, i.e. by dpr squared. I'm not even sure why involve the dpr here, since we are only concerned with width versus height. In any case, it's causing the rendering to appear squashed on my retina iMac.

Changing the line to

    this.threeCamera.aspect = renderer.domElement.width / renderer.domElement.height;

fixes the issue.

**Comment by paulmg** [comment]
You have to set the `dpr` in the config file to target your device, which for retina I think is 2. There is probably a better way to do this and I am surprised it works without it. I recall needing this for retina devices to not look squished. I'll have to take a look later.

**Comment by paulmg** [comment]
Yeah that's right, I forgot it grabbed it dynamically. It looks like this has either changed or was just wrong before. I'll merge your PR in. Thanks
