### ISSUE TITLE
animation.js is either wrong or misleading

### ISSUE THREAD

**Issue by rtpHarry** [paulmg/ThreeJS-Webpack-ES6-Boilerplate#15]
The `animation.js` helper has this for the constructor:
```
  constructor(obj, clip) {
    // Object with animations
    this.obj = obj;

    // Initialize animation mixer
    this.mixer = new THREE.AnimationMixer(this.obj);

    // Simple animation player
    this.playClip(clip);
  }
```

It's included in the repo as a helper but there isn't any usage example. 

The `// Object with animations` comment implied to me that the next level up object should be supplied than what it is actually expecting. 

All it actually wants is a scene not an object with animations.

For example, the gltf loader will give you back an "object with animations" that is something like `gltf { scene, animations, etc }` so I was passing that in and it wasn't working.

When I found the link below, I realised that it actually just wanted the `gltf.scene` passing in, which doesn't actually contain any animations:

https://discourse.threejs.org/t/gltfloader-fails-to-load-my-animation/2703/3

**Comment by paulmg** [comment]
Ah ok, seems like it's changed since I last used the animation with this. Thanks for clarifying.
