### ISSUE TITLE
Error: Tutorial will not start / cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by mldangelo** [paulmg/ThreeJS-Webpack-ES6-Boilerplate#17]
Using Node 8.12.0 on macOS Mojave I ran:

1. `npm install`
2. `npm run dev`

and received the following error message: 

```bash
projects/ThreeJS-Webpack-ES6-Boilerplate/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
```

<img width="834" alt="screen shot 2018-10-22 at 1 58 56 am" src="https://user-images.githubusercontent.com/7235481/47279323-1f364700-d59e-11e8-9c81-bb918f578cb8.png">

**Comment by paulmg** [comment]
Hmm, not sure what's going on here. Could be an issue with either Node or Mojave. I'll try and update Node later and give it a spin, see if I get the same error. Mojave will be more problematic to replicate.

**Comment by mldangelo** [comment]
@paulmg I don't think the Mojave part is important. Which operating system and which version of node do you recommend using?

**Comment by paulmg** [comment]
Thanks! Got caught up in other things and wasn't able to look into this. I'll merge your PR in now.

**Comment by igghera** [comment]
No problem, contributing is a pleasure :)

Il giorno gio 6 dic 2018 alle ore 22:54 Paul Graffam <
notifications@github.com> ha scritto:
