### ISSUE TITLE
How do you have done this?

### ISSUE THREAD

**Issue by yanlee26** [paulmg/ThreeJS-Webpack-ES6-Boilerplate#2]
I think this is such a perfect job,but can you tell me how I  do to understand it in detail?Many thanks!

**Comment by paulmg** [comment]
Hey @yanlee26 , thank you. Is there something in particular you would like to know? I have added some comments throughout the code that will hopefully explain most of what is going on.

**Comment by yanlee26** [comment]
Well ,thanks @paulmg .I am a freshman in three.js's new-world,and I want to abstract some interfaces to other team mumbers.I feel consused to start,to be honest,webpack seems too hard to get good knowledge of it .
To be short,would you please give me some pieces of advice about how to use webpack,three.js,and nodejs???This maybe hard to say,but I really inneed,many thanks @paulmg
