### ISSUE TITLE
Question about build

### ISSUE THREAD

**Issue by VinAr22** [paulmg/ThreeJS-Webpack-ES6-Boilerplate#20]
Hi! Great boilerplate! If i run command **npm run build**  is webpack should run server 8080? Also if i runing it, its appears too many errors in different modules like this: 

`C:\Users\Аркадий\Desktop\Project\src\js\utils\orbitControls.js
     1:1   warning  'module' is not defined            no-undef
    13:12  warning  'THREE' is defined but never used  no-unused-vars
   155:9   warning  Unexpected console statement       no-console
   175:9   warning  Unexpected console statement       no-console
   195:9   warning  Unexpected console statement       no-console
   297:4   warning  Unnecessary semicolon              no-extra-semi
   812:4   warning  Unnecessary semicolon              no-extra-semi
   839:9   warning  Unexpected console statement       no-console
  1012:9   warning  Unexpected console statement       no-console
  1019:9   warning  Unexpected console statement       no-console
  1030:9   warning  Unexpected console statement       no-console
  1037:9   warning  Unexpected console statement       no-console
  1048:9   warning  Unexpected console statement       no-console
  1055:9   warning  Unexpected console statement       no-console
  1066:9   warning  Unexpected console statement       no-console
  1073:9   warning  Unexpected console statement       no-console
  1084:9   warning  Unexpected console statement       no-console
  1091:9   warning  Unexpected console statement       no-console
  1102:9   warning  Unexpected console statement       no-console
  1109:9   warning  Unexpected console statement       no-console

✖ 37 problems (0 errors, 37 warnings)
  0 errors and 6 warnings potentially fixable with the `--fix` option.`

Thank you!

**Comment by paulmg** [comment]
Hey, sorry I haven't responded yet. The warnings are to be expected as that is coming from a third party component I included. You can certainly clean it up if you want but it is mostly minor stuff like console logs. 
Running the build compiles the entire project for you into the necessary files and folders. You can then just open the index.html file in the build directory and it will run the app through a browser. You don't need to start the webpack server; that is there for when you want to do dev work.

**Comment by VinAr22** [comment]
Thank you for your reply! I ask it because i just started to learn webpack. Also i have another issues. When i start dev server and try to edit scss/html files, changes is not updates in browser. In this case i need to restart dev server. What i should do? Thank you again.

**Comment by paulmg** [comment]
Hmm that's weird. It should reload on changes (although not positive it would with html updates). I'll have to take a look at some point and see if there's something messed up but I recall it updating for sure with scss and js changes. Are you getting any errors?

**Comment by VinAr22** [comment]
Hi! There are no errors, except for those that I wrote earlier. The only thing I see in the console is this message:
`client:126 [WDS] Warnings while compiling.
warnings @ client:126
(anonymous) @ socket.js:47
sock.onmessage @ SockJSClient.js:63
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
client:135 asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  vendors.app.js (2.66 MiB)
warnings @ client:135
(anonymous) @ socket.js:47
sock.onmessage @ SockJSClient.js:63
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
client:135 entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (2.78 MiB)
      app.js
      vendors.app.js
      ../css/main.css
      main.app.js

warnings @ client:135
(anonymous) @ socket.js:47
sock.onmessage @ SockJSClient.js:63
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
client:135 webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/`
