### ISSUE TITLE
ThreeJS version update to r115?

### ISSUE THREAD

**Issue by rohitbhirud** [paulmg/ThreeJS-Webpack-ES6-Boilerplate#29]

**Comment by paulmg** [comment]
When I get some time I'll take a look at updating three.js.

**Comment by Teo0303** [comment]
Yeah, this is a necessary feature. I am currently working with this repo but there were some issues with gltf loader. When I upgraded to v115 everything worked perfectly. Unfortunately, build process is failing because of the three js version upgrade. Thank you beforehand

**Comment by Teo0303** [comment]
> When I get some time I'll take a look at updating three.js.

I need your help bro. Please update to r115 asap brooo😭

**Comment by paulmg** [comment]
Sorry, it took forever for me to find the time to get to this. I just updated all the packages to latest with the newest release and I added the ability to load via GLTF. Let me know if you see any issues after using that release.
