### ISSUE TITLE
Uncaught TypeError: three__WEBPACK_IMPORTED_MODULE_0__.CSS3DObject is not a constructor

### ISSUE THREAD

**Issue by neoshamangames** [paulmg/ThreeJS-Webpack-ES6-Boilerplate#32]
I'm trying to incorporate this example
https://codepen.io/asjas/pen/pWawPm
into the project and I'm getting an the above error.  I read that CSS3DObject may not be installed by default. How can I add support? Thanks.

**Comment by paulmg** [comment]
Hey, this seems outside the scope of this boilerplate. Not sure why you are getting that to be honest, it could be for a myriad of reasons. Have you tried taking a look here for possible answers: https://github.com/mrdoob/three.js/issues/16095
