### ISSUE TITLE
<div class="dg main a" style="width: 245px;"> blocks orbitControls

### ISSUE THREAD

**Issue by Callet91** [paulmg/ThreeJS-Webpack-ES6-Boilerplate#34]
Hi there, 

I noticed that the GUI blocks the renderer and further the orbitControls. 

![image](https://user-images.githubusercontent.com/37737427/104851576-1b690a80-58f6-11eb-8502-bc5e737e7ec3.png)

Did a quick dirty fix to solve this by adding the following to src/css/app/_main.scss (if someone else experience the same issue): 

```css
.dg.main.a {
  height: auto; 
}
```

**Comment by paulmg** [comment]
Fixed in latest release
