### ISSUE TITLE
"npm run dev" not serving in-memory files so browser not reloading re-compiled changes

### ISSUE THREAD

**Issue by designbyjosh** [paulmg/ThreeJS-Webpack-ES6-Boilerplate#38]
### Expected behaviour
1. Execute `npm run dev`
2. Browser opens, app is running
3. Change app source
4. Code recompiles
5. Refresh browser, **changes are implemented**

### Actual behaviour
1. Execute `npm run dev`
2. Browser opens, app is running
3. Change app source
4. Code recompiles
5. Refresh browser, **nothing changes**

### Debugging

1. Execute `npm run dev`
2. Once compiled and running in browser, delete all content from `src/public/js/main.bundle.js` and save
3. Refresh browser and observe that "Loading..." remains on-screen
4. Make a change to `src/app.js` e.g. add a `console.log("FOO")` and save
5. Observe that the app is recompiled
6. Refresh the browser and observe that there is no change, "Loading..." remains on-screen
7. Observe that `src/public/js/main.bundle.js` remains empty
8. Navigate to `http://localhost:8080/webpack-dev-server`
9. Click `main.bundle.js` and observe the loaded resource is at `http://localhost:8080/jsmain.bundle.js`

### Suggested fix

Add forward slashes so that `publicPath: 'js',` becomes `publicPath: '/js/',` in `webpack.config.js`.
After doing this, the expected behaviour happens, and the resource linked from  `main.bundle.js` on `http://localhost:8080/webpack-dev-server` properly loads at `http://localhost:8080/js/main.bundle.js`

https://github.com/paulmg/ThreeJS-Webpack-ES6-Boilerplate/blob/b52ad3e7b9b4e6fd9d1a9b95ba0b9dec253d8628/webpack.config.js#L49-L58

**Comment by paulmg** [comment]
Ah thanks, I was trying to get that to work actually just recently. Really appreciate the very detailed description and solution. I'll have to implement this later and see how it works but feel free to create a PR with this change if you'd like.

**Comment by designbyjosh** [comment]
Awesome, I've added the PR. Just to note that I've not conducted any more extensive testing as am getting to grips with webpack. Thanks for this repo, it's great!
