### ISSUE TITLE
ReferenceError: event is not defined

### ISSUE THREAD

**Issue by weiserhei** [paulmg/ThreeJS-Webpack-ES6-Boilerplate#4]
When I run your example on my windows machine, using ``npm run dev``, I get ``ReferenceError: event is not defined``:

![grafik](https://user-images.githubusercontent.com/7581732/39663497-ace4d7f6-5074-11e8-8599-9e5622da7e19.png)

**Comment by paulmg** [comment]
Are you still having this issue @weiserhei? I will need some more info such as browser version, node version, and any previous steps you might've done.

**Comment by weiserhei** [comment]
This happens on my machine when i press any key. For example `h`, hiding dat.gui but logging this error.

> Firefox 59
> Windows 10
> node v6.11.3

**No Error in MS Edge**.
AFAIK I get this Error on Firefox on CentOS too, can verify tomorrow.

I havent researched this except from looking at `keyboard.js` without too much effort. 


I have to say Im novice to webpack and your boilerplate was my starting point, I couldnt get threejs+webpack setup other way and migrating now an existing project using your code as base. There are some more questions already arisen, if you want I create more Issues and PRs ✌️ 

Not to be confused about the last words, the Error also happens in your unmodified example.

**Comment by weiserhei** [comment]
Fixed this, see:
https://github.com/paulmg/ThreeJS-Webpack-ES6-Boilerplate/pull/8

**Comment by paulmg** [comment]
Ah great, I'll take a look later this weekend and merge it in. Thanks for taking care of these issues.
